_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.1
            "6": 4.38.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
alpha:
    value: 0.3
batch_size:
    value: 8
fp16:
    value: true
gradient_accumulation_steps:
    value: 2
learning_rate:
    value: 0.0003
max_steps:
    value: 5000
seed:
    value: 42
